<?php

declare(strict_types=1);

namespace Stories\Shared\Error;

use InvalidArgumentException;
use Stories\Shared\Error\ApiException;
use Throwable;

enum ApiErrorCode: string
{
    case INVALID_CREDENTIALS = 'INVALID_CREDENTIALS';
    case USER_EXISTS = 'USER_EXISTS';
    case CURRENT_PASSWORD_INVALID = 'CURRENT_PASSWORD_INVALID';
    case PASSWORD_CHANGED = 'PASSWORD_CHANGED';
    case NO_FIELDS_TO_UPDATE = 'NO_FIELDS_TO_UPDATE';
    case USER_NOT_FOUND = 'USER_NOT_FOUND';
    case MISSING_BEARER_TOKEN = 'MISSING_BEARER_TOKEN';
    case INVALID_TOKEN_FORMAT = 'INVALID_TOKEN_FORMAT';
    case INVALID_TOKEN_SIGNATURE = 'INVALID_TOKEN_SIGNATURE';
    case INVALID_TOKEN_PAYLOAD = 'INVALID_TOKEN_PAYLOAD';
    case INVALID_TOKEN_CLAIMS = 'INVALID_TOKEN_CLAIMS';
    case TOKEN_EXPIRED = 'TOKEN_EXPIRED';
    case INVITE_CODE_NOT_FOUND = 'INVITE_CODE_NOT_FOUND';
    case OWNER_ALREADY_HAS_ROOM = 'OWNER_ALREADY_HAS_ROOM';
    case USER_ALREADY_HAS_ACTIVE_ROOM = 'USER_ALREADY_HAS_ACTIVE_ROOM';
    case ROOM_PASSWORD_REQUIRED = 'ROOM_PASSWORD_REQUIRED';
    case ROOM_PASSWORD_INVALID = 'ROOM_PASSWORD_INVALID';
    case ROOM_IS_FULL = 'ROOM_IS_FULL';
    case USER_NOT_IN_ROOM = 'USER_NOT_IN_ROOM';
    case ROOM_NOT_FOUND = 'ROOM_NOT_FOUND';
    case INVITE_CODE_GENERATION_FAILED = 'INVITE_CODE_GENERATION_FAILED';
    case ONLY_OWNER_CAN_MANAGE_ROOM = 'ONLY_OWNER_CAN_MANAGE_ROOM';
    case OWNER_CANNOT_BE_REMOVED = 'OWNER_CANNOT_BE_REMOVED';
    case CANNOT_TRANSFER_OWNERSHIP_TO_SELF = 'CANNOT_TRANSFER_OWNERSHIP_TO_SELF';
    case ONLY_PLAYERS_CAN_BE_KICKED = 'ONLY_PLAYERS_CAN_BE_KICKED';
    case ONLY_ACTIVE_PLAYERS_CAN_TOGGLE_READY = 'ONLY_ACTIVE_PLAYERS_CAN_TOGGLE_READY';
    case SPECTATORS_CAN_ONLY_BE_KICKED = 'SPECTATORS_CAN_ONLY_BE_KICKED';
    case USER_BLOCKED_IN_ROOM = 'USER_BLOCKED_IN_ROOM';
    case INVITE_CODE_ROTATE_COOLDOWN = 'INVITE_CODE_ROTATE_COOLDOWN';
    case VALIDATION_ERROR = 'VALIDATION_ERROR';
    case UNKNOWN_ERROR = 'UNKNOWN_ERROR';

    public static function fromThrowable(Throwable $throwable): self
    {
        if ($throwable instanceof ApiException) {
            return $throwable->errorCode;
        }
        if ($throwable instanceof InvalidArgumentException) {
            return self::VALIDATION_ERROR;
        }

        return self::UNKNOWN_ERROR;
    }
}
